name: Django CI

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd eval_website
        pip install -r requirements.txt

    - name: Run first 5 lines of setup.sh script
      run: |
        head -n 27 setup.sh > first_five_lines.sh
        chmod +x first_five_lines.sh
        echo "127.0.0.1" | ./first_five_lines.sh

    - name: Change to eval_website directory
      run: cd eval_website

    - name: Run Tests
      run: |
        cd eval_website
        python manage.py test main
